@startuml
title Modelando o iPhone com UML: Funções de Músicas, Chamadas e Internet

skinparam classAttributeIconSize 0
interface "Reprodutor Musical" as ReprodutorMusical {
  -Musica[] musicas
  +tocarMusica(): void
  +pausarMusica(): void
  +selecionarMusica(): void
}

class Musica {
  nome: String
  caminho: String
}

class Contato {
  nome: String
  numero: String
}

interface "Aparelho Telefônico" as AparelhoTelefonico {
  -Contato[] contatos
  -SinalMovel(): Boolean
  +ligar(): void
  +atender(): void
  +desligar(): void
  +iniciarCaixaPostal(): void
}

interface "Navegador de Internet" as NavegadorInternet {
  -AcessoInternet(): Boolean
  +exibirPagina(): void
  +adicionarNovaAba(): void
  +atualizarPagina(): void
}

entity "IPhone" as IPhone {}

entity "Opera" as Opera {}
entity "Safari" as Safari {}

entity "Nokia 6600" as Nokia6600 {}
entity "Ericsson T65" as EricssonT65 {}

entity "Walkman" as Walkman {}
entity "Creative Zen Micro" as CreativeZenMicro {}

IPhone --> AparelhoTelefonico
IPhone --> NavegadorInternet
IPhone --> ReprodutorMusical
ReprodutorMusical --o Musica
AparelhoTelefonico <-- Nokia6600
AparelhoTelefonico <-- EricssonT65
AparelhoTelefonico --o Contato

ReprodutorMusical <-- Walkman
ReprodutorMusical <-- CreativeZenMicro

NavegadorInternet <-- Opera
NavegadorInternet <-- Safari

@enduml